# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robocrane_telemetry.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'robocrane_telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19robocrane_telemetry.proto\x12\trobocrane\"\xd9\x04\n\x12RobocraneTelemetry\x12\x14\n\x0ctimestamp_ms\x18\x01 \x01(\x04\x12\t\n\x01q\x18\x02 \x03(\x02\x12\r\n\x05q_dot\x18\x03 \x03(\x02\x12\x0e\n\x06q_ddot\x18\x04 \x03(\x02\x12\x0e\n\x06q_norm\x18\x15 \x03(\x02\x12\x11\n\tqdot_norm\x18\x16 \x03(\x02\x12\x0b\n\x03q_d\x18\x17 \x03(\x02\x12\x0e\n\x06qdot_d\x18\x18 \x03(\x02\x12\x0f\n\x07qddot_d\x18\x19 \x03(\x02\x12\x0e\n\x06pos_ef\x18\x05 \x03(\x02\x12\x0e\n\x06yaw_ef\x18\x06 \x01(\x02\x12\x10\n\x08goal_pos\x18\x07 \x03(\x02\x12\x10\n\x08goal_yaw\x18\x08 \x01(\x02\x12\r\n\x05\x65_pos\x18\t \x03(\x02\x12\r\n\x05\x65_yaw\x18\n \x01(\x02\x12\x0b\n\x03pos\x18\x0b \x03(\x02\x12\x0b\n\x03yaw\x18\x0c \x01(\x02\x12\x0e\n\x06\x61_prev\x18\r \x03(\x02\x12\x16\n\x0esurface_normal\x18\x0e \x03(\x02\x12\x0e\n\x06z_axis\x18\x0f \x03(\x02\x12\x11\n\tforce_ext\x18\x10 \x03(\x02\x12\x12\n\nwrench_ext\x18\x11 \x03(\x02\x12\x12\n\nforce_norm\x18\x12 \x01(\x02\x12\x14\n\x0ctau_res_norm\x18\x13 \x01(\x02\x12\x12\n\naction_raw\x18\x14 \x03(\x02\x12\x0f\n\x07tau_raw\x18  \x03(\x02\x12\x0e\n\x06reward\x18\x1e \x01(\x02\x12\x44\n\x0creward_terms\x18\x1f \x03(\x0b\x32..robocrane.RobocraneTelemetry.RewardTermsEntry\x1a\x32\n\x10RewardTermsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robocrane_telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOCRANETELEMETRY_REWARDTERMSENTRY']._loaded_options = None
  _globals['_ROBOCRANETELEMETRY_REWARDTERMSENTRY']._serialized_options = b'8\001'
  _globals['_ROBOCRANETELEMETRY']._serialized_start=41
  _globals['_ROBOCRANETELEMETRY']._serialized_end=642
  _globals['_ROBOCRANETELEMETRY_REWARDTERMSENTRY']._serialized_start=592
  _globals['_ROBOCRANETELEMETRY_REWARDTERMSENTRY']._serialized_end=642
# @@protoc_insertion_point(module_scope)
